# This Dockerfile builds the API only.

FROM python:3.9
WORKDIR /app

COPY api/.flaskenv api/requirements.txt api/association_rules.csv.xz api/helpers.py api/main.py api/models.py api/preprocess_instacart_market_basket_analysis_data.py api/products.csv.xz api/repositories.py api/services.py ./
RUN pip install -r ./requirements.txt
RUN pip install gunicorn
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "main:app", "--preload", "--timeout", "300"]
